// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createdUser = `-- name: CreatedUser :one
INSERT INTO users (id, created_at,updated_at,name)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, name
`

type CreatedUserParams struct {
	ID        uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Name      string
}

func (q *Queries) CreatedUser(ctx context.Context, arg CreatedUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createdUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
